---
# tasks file for php

  - name: Atualiza o parametro max_execution_time
    lineinfile:
      dest: /etc/php/7.3/apache2/php.ini
      state: present
      backup: yes
      backrefs: yes
      regexp: "max_execution_time = 30"
      line: "max_execution_time = 60"
    notify:
    - reinicia apache